use_frameworks!

target 'DYObject_Example' do
  pod 'DYObject', :path => '../'

  target 'DYObject_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
